### ISSUE TITLE
lol how do I get rid of this now

### ISSUE THREAD

**Issue by mwvd** [helloitsdan/kawaiiberpunk#1]
![screen shot 2016-01-10 at 10 24 05 pm](https://cloud.githubusercontent.com/assets/4127151/12226367/e0788904-b7e8-11e5-9349-079856bac5ce.png)

so I did it twice by accident and the first didn't work (linked wrong) - how do I clear all this now so I can start again?

**Comment by mwvd** [comment]
I figured this out by using:

```
touch ~/.bash_profile; open ~/.bash_profile
```

then editing this in textedit

**Comment by helloitsdani** [comment]
ah!! i'm glad you figured it out! i'm sorry i was asleep for ages

**Comment by mwvd** [comment]
ahahaha me too dwthanks ✨

On Mon, Jan 11, 2016 at 1:46 AM -0800, "dani quinn sexton" notifications@github.com wrote:

ah!! i'm glad you figured it out! i'm sorry i was asleep for ages
